# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.290
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --follow-imports=skip, --config-file, pyproject.toml]

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v7.3.0
    hooks:
      - id: cspell
        args: [
          --no-must-find-files,
          --no-progress,
          --no-summary,
          --exclude .cspell.json
        ]

  - repo: local
    hooks:
      - id: unittests
        name: run unit tests
        entry: python -m pytest
        language: system
        pass_filenames: false
        always_run: true
        args: []
